language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: A8xVobzJlle2swPuFeAPhCRtOiTNCcD2D6GD8G1+fdvIJiy6EPtuCsquN85SmfGvKLw61CW/8z2pmwH2JqCO4VdijQbejW3IpfOm+NfILHG74pKTJqpknkEqBDfcVi+2+F26CfsikuVmwg7jkwZiKZgg5Dw91XiDG4120PK6olHarc0JYrlFffAfnUINx792oXTIxbGrHswe5HwBodhRnC2/+iol+kgAC+tGfcirIniu5MzyjVaarBX3qrJVw3v7TWG9wGiPSvLBuKX8WUfejbhl1hXW6JOpWfy5qgMntGRn192lC6fRSiBdUCWXGHCWc40Crv6rQkRXzN/pmKPGf1jwOToBQfcnxe6+9zC7i0x66vaSPEzLOMR5hwBTs819HkwxJ35K0JyGXXA9PNdG7VdBdkvbJmLOrYu0MT7Cx5r1oXKhb0ccQDTZhMncvSybvJbsQOBTmjirJi7f5sgd8+voNvtNILWRTlqtXf80DDmilw5dcRCa2fFCAQu1y0BZxnm6t1SnTMsxTRiVSdJA1PoVoJ9D2orQIEx1t+x1XvmkY+C9xNFqXImnRNVwAre+uBwyFi7B1cMxNyyrD5mH2RxI2AM3+U25SCPVjc5QHewK1whyyEJX4/86z0MEp3sh5X/vJtbDWBWSfd96bkwrRTtKLBXyqDumVLawjNJSkdY=
  app: netflix-blog-capstone
  on:
    repo: mmpal78/netflix-blog-capstone
